"""
Stamps wrapper fields onto extracted events and atoms.

Wrapper fields are not generated by the model — they are administrative
metadata added by the pipeline after extraction:

  event_id, atom_id       — globally unique sequential IDs (persisted across runs)
  version                 — schema version
  atom_status             — always "draft" until human review
  origin                  — article provenance
  review_process          — audit trail (model + timestamp + human review status)
"""

from datetime import datetime, timezone


SCHEMA_VERSION = "v1.0"


def stamp_records(
    events: list[dict],
    atoms: list[dict],
    origin: dict,
    model_id: str = "unknown",
    org_prefix: str = "",
    event_counter_start: int = 1,
    atom_counter_start: int = 1,
) -> tuple[list[dict], list[dict]]:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if not org_prefix:
        org = origin.get("organization", "UNK")
        org_prefix = _make_prefix(org)

    event_label_to_id = {}

    stamped_events = []
    for i, event in enumerate(events):
        event_id = f"{org_prefix}-EVT{event_counter_start + i:04d}"
        label = event.get("event_label", "")
        if label:
            event_label_to_id[label] = event_id

        stamped = {
            "event_id": event_id,
            "version": SCHEMA_VERSION,
            **event,
            "origin": _build_origin(origin),
            "review_process": _build_review(model_id, now),
        }
        stamped_events.append(stamped)

    stamped_atoms = []
    for i, atom in enumerate(atoms):
        atom_id = f"{org_prefix}-ATM{atom_counter_start + i:04d}"

        event_label = atom.get("event_label", "")
        if isinstance(event_label, list):
            event_id = [event_label_to_id.get(lbl, "") for lbl in event_label]
            event_id = [eid for eid in event_id if eid]
        else:
            event_id = event_label_to_id.get(event_label, "")

        stamped = {
            "atom_id": atom_id,
            "event_id": event_id,
            "version": SCHEMA_VERSION,
            "atom_status": "draft",
            **atom,
            "origin": _build_origin(origin),
            "review_process": _build_review(model_id, now),
        }
        stamped_atoms.append(stamped)

    return stamped_events, stamped_atoms


def _build_origin(origin: dict) -> dict:
    return {
        "url": origin.get("url", ""),
        "title": origin.get("title", ""),
        "journalist": origin.get("journalist", ""),
        "organization": origin.get("organization", ""),
        "created_at": origin.get("created_at", ""),
    }


def _build_review(model_id: str, timestamp: str) -> dict:
    return {
        "automated_annotation": {
            "annotated_by": model_id,
            "timestamp": timestamp,
        },
        "human_review": {
            "status": "pending",
        }
    }


def _make_prefix(org_name: str) -> str:
    words = org_name.upper().split()
    if len(words) >= 3:
        return "".join(w[0] for w in words[:3])
    elif len(words) == 2:
        return words[0][:2] + words[1][0]
    elif len(words) == 1:
        return words[0][:3]
    return "UNK"
